name: On push, doc-test package
on:
  push:
    branches:
      - main
    paths:
      - dwh_oppfolging/**
      - pyproject.toml
  pull_request:
    branches:
      - main
    paths:
      - dwh_oppfolging

jobs:
  install_lint_and_test:
    runs-on: 
      ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest dwh_oppfolging
